/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package contador;
import javax.swing.*;
import java.io.*;
import java.util.ArrayList;
/**
 *
 * @author CompuFire
 */
public class frm_contador extends javax.swing.JFrame {

    /**
     * Creates new form frm_contador
     */
    public frm_contador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_cadenaTexto = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btn_archivo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtA_archivo = new javax.swing.JTextArea();
        btn_procesar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtA_resultado = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Cadena");

        btn_archivo.setText("Subir archivo");
        btn_archivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_archivoActionPerformed(evt);
            }
        });

        txtA_archivo.setEditable(false);
        txtA_archivo.setColumns(20);
        txtA_archivo.setRows(5);
        jScrollPane1.setViewportView(txtA_archivo);

        btn_procesar.setText("Procesar");
        btn_procesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_procesarActionPerformed(evt);
            }
        });

        txtA_resultado.setEditable(false);
        txtA_resultado.setColumns(20);
        txtA_resultado.setRows(5);
        jScrollPane2.setViewportView(txtA_resultado);

        jLabel2.setText("Archivo adjuntado");

        jLabel3.setText("Texto procesado");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_archivo)
                                .addGap(29, 29, 29)
                                .addComponent(btn_procesar, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(91, 91, 91)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_cadenaTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_cadenaTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_archivo)
                            .addComponent(btn_procesar))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(9, 9, 9)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_archivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_archivoActionPerformed
    JFileChooser selector = new JFileChooser();
        int opcion = selector.showOpenDialog(this);

        if (opcion == JFileChooser.APPROVE_OPTION) {

            File archivo = selector.getSelectedFile();

            try {
                BufferedReader br = new BufferedReader(new FileReader(archivo));
                String linea;
                String textoCompleto = "";

                while ((linea = br.readLine()) != null) {
                    textoCompleto += linea + "\n";
                }

                br.close();

                txtA_archivo.setText(textoCompleto); // lo coloca en el campo

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error al leer archivo");
            }
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btn_archivoActionPerformed

    private void btn_procesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_procesarActionPerformed
    String texto = "";
    if (!txt_cadenaTexto.getText().trim().isEmpty()) {
        texto = txt_cadenaTexto.getText();
    } else if (!txtA_archivo.getText().trim().isEmpty()) {
        texto = txtA_archivo.getText();
    } else {
        JOptionPane.showMessageDialog(this, "No hay texto para procesar");
        return;
    }
    int palabras = 0;
    int espacios = 0;
    int saltos = 0;
    int vocalMinus = 0;
    int vocalMayus = 0;
    int numeros = 0;
    int signos = 0;
    int vocalTilde = 0;

    // Contadores de diptongos e hiatos
    ArrayList<String> listaDiptongos = new ArrayList<>();
    ArrayList<String> listaHiatos = new ArrayList<>();

    for (int i = 0; i < texto.length(); i++) {
        char c = texto.charAt(i);

        // Espacios
        if (c == ' ') espacios++;

        // Saltos de línea
        if (c == '\n') saltos++;

        // Números
        if (Character.isDigit(c)) numeros++;

        // Signos de puntuación
        if (".,;:¿?¡!()\"'".indexOf(c) != -1) signos++;

        // Vocales minúsculas
        if ("aeiou".indexOf(c) != -1) vocalMinus++;

        // Vocales mayúsculas
        if ("AEIOU".indexOf(c) != -1) vocalMayus++;

        // Vocales con tilde
        if ("áéíóúÁÉÍÓÚ".indexOf(c) != -1) vocalTilde++;
    }

    // Contar palabras
    String[] arregloPalabras = texto.trim().split("\\s+");
    palabras = arregloPalabras.length;

    // 🔥 Buscar diptongos e hiatos
    for (String palabra : arregloPalabras) {

        String p = palabra.toLowerCase();

        // Diptongos comunes
        if (p.matches(".*(ai|au|ei|eu|oi|ou|ia|ie|io|ua|ue|uo).*")) {
            listaDiptongos.add(palabra);
        }

        // Hiatos comunes (con tilde)
        if (p.matches(".*(aí|eí|oí|ía|ío|úa|úe).*")) {
            listaHiatos.add(palabra);
        }
    }

    // Mostrar resultados
    txtA_resultado.setText(
        "Palabras: " + palabras +
        "\nEspacios: " + espacios +
        "\nSaltos de línea: " + saltos +
        "\nVocales minúsculas: " + vocalMinus +
        "\nVocales mayúsculas: " + vocalMayus +
        "\nVocales con tilde: " + vocalTilde +
        "\nNúmeros: " + numeros +
        "\nSignos de puntuación: " + signos +
        "\n\nDiptongos encontrados: " + listaDiptongos +
        "\nHiatos encontrados: " + listaHiatos
    );        // TODO add your handling code here:
    }//GEN-LAST:event_btn_procesarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_contador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_contador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_contador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_contador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_contador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_archivo;
    private javax.swing.JButton btn_procesar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txtA_archivo;
    private javax.swing.JTextArea txtA_resultado;
    private javax.swing.JTextField txt_cadenaTexto;
    // End of variables declaration//GEN-END:variables
}
